Ks 1 2
BrnGLghT/KotlinLessons pull request #2
Opened 2024-03-12 17:16 UTC by BrnGLghT

2024-03-13 17:24 UTC, ievetrovdev requested changes

2024-03-13 17:24 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task2.kt
> +fun main(){
опять же по заданию все ок, но ты снова создал кучу файлов, не относящихся к заданию. 

по первой задаче у тебя сейчас стоит аппрув, соответственно ты ее можешь смержить в мастер ветку. после этого на этой ветке нужно сделать pull из мастера и все изменения из 1 мра подтянутся сюда

2024-03-13 17:25 UTC, BrnGLghT commented on src/main/kotlin/lesson1/lesson1_task2.kt
> +fun main(){
Да, там факап такой на первом задании полностью, я дальше это пофиксил @ievetrovdev

2024-03-14 05:01 UTC, ievetrovdev approved these changes

2024-03-14 16:08 UTC, merged