Ks 2 1
BrnGLghT/KotlinLessons pull request #6
Opened 2024-03-12 19:14 UTC by BrnGLghT

2024-03-14 06:44 UTC, ievetrovdev requested changes

2024-03-14 06:44 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task1.kt
> +    val avgGrade: Double = (3.0 + 4.0 + 3.0 + 5.0) / 4.0
Все таки не совсем корректно с точки зрения логики, количество студентов не может быть вещественным числом (дробным).
Однако, баллы могли бы быть дробными, или же можно применить .toFloat() для суммы оценок в момент подсчета

2024-03-15 05:53 UTC, merged

2024-03-15 05:56 UTC, BrnGLghT commented
Факап, не ту ветку смерджил. Пересоздал ПР https://github.com/BrnGLghT/KotlinLessons/pull/20

2024-03-15 07:01 UTC, ievetrovdev reviewed
Бывает, все правильно